[package]
name = "donovim"
version = "0.1.0"
authors = ["Donovan Dicks <donovan.dicks@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
unicode-segmentation = "1"
